services:
  db:
    image: postgres:14.13-bookworm
    environment:
      POSTGRES_DB: gophkeeper
      POSTGRES_USER: gophkeeper
      POSTGRES_PASSWORD: gophkeeper
    ports:
      - 5432:5432
  minio:
    image: quay.io/minio/minio
    hostname: minio
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "12345678"
    volumes:
      - ./data:/data
    command: minio server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
