# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ "dev" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: make

    - name: Test
      run: go test -v ./...

    - name: Binary artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bin-without-source
        path: |
          cmd/gophkeeper
          cmd/client/
          !cmd/**/*.go
          
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cmd/gophkeeper
          cmd/client/
          !cmd/**/*.go
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

